@startuml

Turista "1" -- "1" Endereco
Especie "1" -- "1" Turista
Turista "1" -- "*" Reserva
Turista "1" -- "*" RegistroViagem
Reserva "1" -- "1" Acomodacao
Turista "1" -- "*" Passeio
Passeio "1" -- "1" PontoTuristico
PontoTuristico "*" -- "1" Planeta
Turista "1" -- "*" Servico

class Servico {
    String descricao
    String nome
    String telefone
    String tipo
}

class Reserva {
    Date dataPrevista
    float valor
}

class Acomodacao {
    float valor
    String descricao
}

class RegistroViagem {
    Date dataChegada
    Date dataPartida
    Date dataPrevistaPartida
}

class Passeio {
    String descricao
    String nome
    String valor
}

class Endereco {
    String pais
    String latitude
    String longitude
}

class PontoTuristico {
    String descricao
    String imagem
    String nome
    String valor
}

class Planeta {
    String nome
    String constelacao
}

class Especie {
    String nome
    String descricao
}

class Turista {
    String nome
    String registroInterplanetario
    Endereco endereco
}
@enduml
